In [ ]:
#Q1. Explain the purpose and advantages of NumPy in scientific computing and data analysis. 
#How does it enhance Python's capabilities for numerical operations ?

#Ans- 1.NumPy stands for "Numerical Python" and it is the standard python library used for working with arrays, linear algebra and other numerical computations.
#2.NumPy is a fundamental library in Python for scientific computing.
#3.It offers powerful features for working with multidimensional arrays and performing various mathematical operations efficiently.
#4. NumPy is an open source Python librabry that has a wide range of inbuilt functions. 
#5.Numpy is homogeneous, it can store only same data type.
#6.Numpy faster than python lists because NumPy arrays are stored in a single continuous location in memory, making it very easy for programs to access and manipulate them.
#7.NumPy enhances the python's capabilities for numerical operations because numPy is built using c programming language and c is one of the fastest programming language after c++.
#Advantages are:-
#1.NumPy is ideal for handling large amounts of homogeneous(same-type) data, offering significant improvements in speed and memory efficiency.
#2.It also provides high-level syntax for a wide range of numerical operations, making it a powerful tool for scientific computing and data processing on the CPU.

In [ ]:
#Q2- Compare and contrast np.mean() and np.average() functions in NumPy. When would you use one over the other?

In [3]:
import numpy as np
# if weight of arrays are given then the mean and average are different else both are same.
# in average weights are used

In [5]:
arr = np.random.randint(1,5, size = (3,4))
np.average(arr)

2.75

In [7]:
arr

array([[4, 3, 2, 4],
       [3, 4, 1, 2],
       [4, 1, 3, 2]])

In [9]:
np.average(arr)

2.75

In [11]:
np.mean(arr)

2.75

In [ ]:
#Q3. Describe the methods for reversing a NumPy array along different axes. Provide examples for 1D and 2D
#arrays.
#Ans- We can reverse the matrix in many ways
#1. One dimensional row array Same as list reversing,
#2. with the help of  flip inbuilt function 

In [14]:
arr1 = np.array([1, 2, 3, 4])
reverse_arr1 = arr1[::-1]

In [16]:
reverse_arr1

array([4, 3, 2, 1])

In [18]:
arr2 = np.array([1, 2, 3])
reverse_arr2 = arr2[::-1]

In [20]:
reverse_arr2

array([3, 2, 1])

In [22]:
arr1 =  np.array([1, 2, 3, 4])
reverse_arr1 = np.flip(arr1)
print("arr1        :", arr1)
print("reverse_arr1:", reverse_arr1)

arr1        : [1 2 3 4]
reverse_arr1: [4 3 2 1]


In [24]:
reverse_arr1

array([4, 3, 2, 1])

In [26]:
arr3 = np.array([[1,5,6],[1,2,3],[4, 5, 6]])
reverse_arr3 = np.flip(arr3,axis = 0) # axis = 0 means y-axis 
print("arr3        :", arr3)    
print("reverse_arr3:", reverse_arr3)

arr3        : [[1 5 6]
 [1 2 3]
 [4 5 6]]
reverse_arr3: [[4 5 6]
 [1 2 3]
 [1 5 6]]


In [28]:
arr3 = np.array([[1,5,6],[1,2,3],[4, 5, 6]])
reverse_arr3 = np.flip(arr3,axis = 1) # axis = 1 means x-axis 
print("arr3        :", arr3)    
print("reverse_arr3:", reverse_arr3)

arr3        : [[1 5 6]
 [1 2 3]
 [4 5 6]]
reverse_arr3: [[6 5 1]
 [3 2 1]
 [6 5 4]]


In [ ]:
#Q4. How can you determine the data type of elements in a NumPy array? Discuss the importance of data types in memory management and performance.

#Ans-1.With the inbuilt function (dtype) we can determine the data type of any array
#2.NumPy arrays can hold various data types like integers (int),floats(float), strings(str), etc you can specify the data types during creation.
#3. Array is  homogeneous in nature it can store data in continuous nature because all the elements of array are either integer,float or string etc. 
#  Due to which increase 
#  1. Memory Efficieny
#  2.Performance
#  3. Faster mathematical calculation

In [31]:
arr_num = np.array([1, 2, 3, 4])
print(arr_num.dtype)

int32


In [33]:
arr_str = np.array(["Shanu", "rahul", "Kinchu"])
print(arr_str.dtype) # Teh output is <U6 means (<U) is Unicode string and (6) means the longest string

<U6


In [35]:
arr = np.array([1, 2, 3,"Gaf"])
print(arr.dtype)
arr

<U11


array(['1', '2', '3', 'Gaf'], dtype='<U11')

In [37]:
arr_int = np.array([1, 2, 3, 4])
print(arr_int)
print(arr_int.dtype)

[1 2 3 4]
int32


In [ ]:
#Q5. Define ndarrays in NumPy and explain their key features. How do they differ from standard Python lists?

#1. N-Dimensional: The "N" in ndarray stands for the number of dimensions. These dimensions can be anything from 1D (a simple list) to 2D(like a matrix) and beyond. you can create arrays with any number of dimensions, and each dimension can have any number of elements. 
#2. Homogeneous Data: All elements within an ndarray must be of the same data type. Because of this homogeneity ensures efficient memory usage and consistent interpretation of data.
#3. Fixed Size: Once you create an ndarray, its size (i.e., the number of elements along each dimension) remains fixed. You can't dynamically resize it like you would with a Python list.
#4. Indexing and slicing: You can access individual elements, slice, or subarrays within an ndarray using indexing and slicing.
#5 Operations: In array we can perform various task like addition, Matrix multiplication, solve linear equation and statistics and much more operations .
#6. Broadcasting: Broadcasting is a mechanism in NumPy that allows performing operations on arrays of different shapes under certain conditions. 



In [ ]:
#Q6. Analyze the performance benefits of NumPy arrays over Python lists for large-scale numerical operations.

#Ans-1 Data Structures:
# a. Python Lists: Python list are heterogeneous >> it can store many type of data in single list like integer, boolean, float and string all the data are arranged randomly. So it is difficult to find the data.
# b. NumPy Arrays: NumPy arrays are homogeneous>>The elements in a NumPy array are all required to be of the same data type, and thus will be the same size in memory.So, it is easy to find the data.
#2. Memory Allocation:
# a. Python Lists: Each list element is an object containing a pointer to another object. TThis indirection adds overhead
# b. NumPy Arrays: They have extra metadata(like shape, strides and data type)but usually less per_element overhead than lists. The continuous memory layout improves space utilization.


In [ ]:
#Q7. Compare vstack() and hstack() functions in NumPy. Provide examples demonstrating their usage and output.
#vstack :- Add  arrays verically called as vstack
#hstack :- Stack  arrays horizontally(column wise) called as hstack
#All array are of same size 

In [32]:
import numpy as np
ar1 = np.random.randint(1,7, size = (3,4))
ar2 = np.random.randint(1,5 ,size = (3,4))
print("ar1: ", ar1)
print("ar2: ", ar2)

ar1:  [[4 6 5 6]
 [2 1 5 1]
 [2 5 2 5]]
ar2:  [[1 1 2 2]
 [1 2 3 4]
 [1 1 4 4]]


In [34]:
c = np.vstack((ar1,ar2))
c

array([[4, 6, 5, 6],
       [2, 1, 5, 1],
       [2, 5, 2, 5],
       [1, 1, 2, 2],
       [1, 2, 3, 4],
       [1, 1, 4, 4]])

In [40]:
d = np.hstack((ar1,ar2))
d

array([[4, 6, 5, 6, 1, 1, 2, 2],
       [2, 1, 5, 1, 1, 2, 3, 4],
       [2, 5, 2, 5, 1, 1, 4, 4]])

In [57]:
ar3 = np.array([1, 2, 3])
ar4 = np.array([4, 5, 6])
ar5 = np.array([7, 8, 9])
e = np.vstack((ar3, ar4, ar5))
print(e)
f = np.hstack((ar3, ar4, ar5))
f

[[1 2 3]
 [4 5 6]
 [7 8 9]]


array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
#Q8. Explain the differences between fliplr() and flipud() methods in NumPy, including their effects on various array dimensions.

#fliplr()>> Stands from Flip Left-Right
#1. It reverse the order of elements along axis 1 (i.e., horizontally). Imagine it like flipping a matrix from left to right.
#2. Input array, must be atleast 2-D.
#3. Columns are preserved, but appear in a different order than before.

#flipud()>> Stands from Flip Up-Down
#1. flip array in the up/down direction.
#2. The flipud() functions reverses the order of elements along axis 0 (i.e., vertically) up to down.
#3. Input array, must be atleast 2-D.
#4. Rows are preserved, but appear in a different order than before.


In [39]:
import numpy as np
a1 = np.random.randint(2,6, size = (2,3))
print(a1)
a11 = np.fliplr(a1)
print(a11)

[[2 5 4]
 [3 4 3]]
[[4 5 2]
 [3 4 3]]


In [41]:
a2 = np.random.randint(1,5, size = (4,5))
print(a2)
a22 = np.flipud(a2)
print(a22)

[[4 1 3 2 1]
 [3 4 3 3 2]
 [3 2 4 2 3]
 [3 1 4 3 2]]
[[3 1 4 3 2]
 [3 2 4 2 3]
 [3 4 3 3 2]
 [4 1 3 2 1]]


In [ ]:
#Q9. Discuss the functionality of the array_split() method in NumPy. How does it handle uneven splits?

#array_split()>> 1. The numpy.array_split() function is used to split an array into multiple sub-arrays. It's quite similar to the regular numpy.split() method.
#2. It allows for uneven ( numpy.array_split() ) splitting arrays.

In [48]:
import numpy as np
arr1 = np.array([[1, 2, 3, 4],[1, 2,3,6],[1,2,7,8]])
b = np.array_split(arr1,4)
print(arr1)
print("split_array:", b)

[[1 2 3 4]
 [1 2 3 6]
 [1 2 7 8]]
split_array: [array([[1, 2, 3, 4]]), array([[1, 2, 3, 6]]), array([[1, 2, 7, 8]]), array([], shape=(0, 4), dtype=int32)]


In [58]:
arr1 = np.array(([1, 2, 3, 4]))
c = np.array_split(arr1,3)
print(arr1)
print(c)

[1 2 3 4]
[array([1, 2]), array([3]), array([4])]


In [60]:
arr2 = np.arange(8)
print(arr2)
d = np.array_split(arr2,2)
print(d)

[0 1 2 3 4 5 6 7]
[array([0, 1, 2, 3]), array([4, 5, 6, 7])]


In [84]:
arr3 = np.random.randint(2,8, (4,5))
print(arr3)
e = np.array_split(arr3,5, axis = 1)
print(e)

[[2 4 2 5 5]
 [3 5 2 3 6]
 [3 2 5 5 5]
 [4 2 4 6 7]]
[array([[2],
       [3],
       [3],
       [4]]), array([[4],
       [5],
       [2],
       [2]]), array([[2],
       [2],
       [5],
       [4]]), array([[5],
       [3],
       [5],
       [6]]), array([[5],
       [6],
       [5],
       [7]])]


In [ ]:
#Q10. Explain the concepts of vectorization and broadcasting in NumPy. How do they contribute to efficient array operations ?
#1. Vectorization:
# . Vectorization is a powerful concept in NumPy that allows you to perform element-wise operations
#   on entire arrays (or vectors) without explicitly writhin loops. It's like applying an operation 
#  to each element of an array simultaneously.
#  . When you perform an operation (e.g., addition, multiplication,etc.) between two NumPy arrays, 
#    the operation is automatically applied element-wise. This is much more efficient than iterating 
#   through each element manually.
# . The NumPy enhances the python's capabilities for numerical operations because numPy is built 
#    using c programming language and c is one of the fastest programming language after c++.
#2. Broadcasting:
#  . Broadcasting extends the concept of vectorization. It allows NumPy to perform operations on 
#    arrays with different shapes, as long as they are compatible.
#  . When you perform an operation between arrays with different shapes, NumPy automatically 
#    "broadcast" the smaller array to match the shape of the larger one. 
#3. Efficiency Benefits:
#  . Performance: By avoiding explicit loops, vectorized operations are significantly faster. 
#    NumPy's optimized routines take advantage of hardware-specific optimizations.
#  . Readability: Vectorized code is concise and easier to understand. You express your intent 
#    directly without writing boilerplate loop code.
#4. Memory Efficiency:
#  . Broadcasting avoids unnecessary copying of data. It operates on views of the original arrays,
#    minimizing memory usage.
#5. Parallelization: Vectorized operations can be parallelized, utilization multiple CPU cores 
#   efficiency.

In [50]:
a11 = np.random.randint(1,4,(3,4))
print(a11)
print(a11+3)

[[3 3 1 2]
 [3 2 2 3]
 [3 3 1 1]]
[[6 6 4 5]
 [6 5 5 6]
 [6 6 4 4]]


In [54]:
a = np.array([[1,3],[3,4]])
b = np.array([[10,20]])
print(a)
print(b)
print(a+b)

[[1 3]
 [3 4]]
[[10 20]]
[[11 23]
 [13 24]]


In [57]:
#1. Create a 3x3 NumPy array with random integers between 1 and 100. Then, interchange its rows and columns.
import numpy as np
arr = np.random.randint(1,100,(3,3)) 
print(arr)
print("transpose of arr: ", arr.T)

[[17 83 43]
 [20 90 17]
 [28 74 78]]
transpose of arr:  [[17 20 28]
 [83 90 74]
 [43 17 78]]


In [63]:
#2. Generate a 1D NumPy array with 10 elements. Reshape it into a 2x5 array, then into a 5x2 array.
original_array = np.arange(10)
print("original 1D array:")
print(original_array)
print("2x5 array:")
array_new1 = original_array.reshape(2,5)
print(array_new1)
array_new2 = original_array.reshape(5,2)
print("5x2 array:")
print(array_new2)

original 1D array:
[0 1 2 3 4 5 6 7 8 9]
2x5 array:
[[0 1 2 3 4]
 [5 6 7 8 9]]
5x2 array:
[[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]


In [418]:
#3. Create a 4x4 NumPy array with random float values. Add a border of zeros around it, resulting in a 6x6 array.

arr_float = np.random.rand(4,4)
arr_float
result_array =  np.pad(arr_float, pad_width = 1,mode = "constant", constant_values = 0, )
print(result_array)

[[0.         0.         0.         0.         0.         0.        ]
 [0.         0.54158685 0.85132979 0.48507484 0.96604983 0.        ]
 [0.         0.21851606 0.87881    0.30780177 0.18089829 0.        ]
 [0.         0.94184465 0.38775755 0.69111821 0.09876001 0.        ]
 [0.         0.06712463 0.23623291 0.19076673 0.25512093 0.        ]
 [0.         0.         0.         0.         0.         0.        ]]


In [72]:
#4. Using NumPy, create an array of integers from 10 to 60 with a step of 5.
import numpy as np
arr = np.arange(10,61 ,5)
arr

array([10, 15, 20, 25, 30, 35, 40, 45, 50, 55, 60])

In [110]:
#5. Create a NumPy array of strings ['python', 'numpy', 'pandas']. Apply different case transformations
#(uppercase, lowercase, title case, etc.) to each element.
str1 = np.array(["python", "numpy", "pandas"])
uppercase = np.char.upper(str1)
print("uppercase:", uppercase)
lowercase = np.char.lower(str1)
print("lowercase:", lowercase)
swapcase = np.char.swapcase(str1)
print("swapcase:", swapcase)
capitalized = np.char.capitalize(str1)
print("capitalized:", capitalized)

uppercase: ['PYTHON' 'NUMPY' 'PANDAS']
lowercase: ['python' 'numpy' 'pandas']
swapcase: ['PYTHON' 'NUMPY' 'PANDAS']
capitalized: ['Python' 'Numpy' 'Pandas']


In [71]:
#6. Generate a NumPy array of words. Insert a space between each character of every word in the array.

In [101]:

words = np.array(['abracadabra', 'wizardry', 'enchant', 'spellbinding', 'incantation'])
spaced_words = np.array([' '.join(list(word)) for word in words])
print(spaced_words)

['a b r a c a d a b r a' 'w i z a r d r y' 'e n c h a n t'
 's p e l l b i n d i n g' 'i n c a n t a t i o n']


In [91]:
word = "shnjjni"
" ".join(word)

's h n j j n i'

In [136]:
#7. Create two 2D NumPy arrays and perform element-wise addition, subtraction, multiplication, and division.
array2d = np.array(([[1, 25, 35 ,4]]))
array = 5 
print("addition:", array2d + array)
print("Subtraction:", array2d - array)
print("multiplication:", array2d * array)
print("division:", array2d / array)

addition: [[ 6 30 40  9]]
Subtraction: [[-4 20 30 -1]]
multiplication: [[  5 125 175  20]]
division: [[0.2 5.  7.  0.8]]


In [165]:
#8. Use NumPy to create a 5x5 identity matrix, then extract its diagonal elements.
identity_matrix = np.eye(5)
diagonal_elements = np.diag(identity_matrix)
print(identity_matrix)
print(diagonal_elements)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]
[1. 1. 1. 1. 1.]


In [351]:
#9. Generate a NumPy array of 100 random integers between 0 and 1000. Find and display all prime numbers in this array.


Random_int = np.linspace(0, 1001, 100, dtype = int)


num_list = list(Random_int)

# Check prime
for num in num_list:
    count = 0
    for i in range(1, int(num) + 1):
        if num % i == 0:
            count += 1

    if count == 2:
        print(f"{num} is a prime number")
    else:
        print(f"{num} is not a prime number")



0 is not a prime number
10 is not a prime number
20 is not a prime number
30 is not a prime number
40 is not a prime number
50 is not a prime number
60 is not a prime number
70 is not a prime number
80 is not a prime number
91 is not a prime number
101 is a prime number
111 is not a prime number
121 is not a prime number
131 is a prime number
141 is not a prime number
151 is a prime number
161 is not a prime number
171 is not a prime number
182 is not a prime number
192 is not a prime number
202 is not a prime number
212 is not a prime number
222 is not a prime number
232 is not a prime number
242 is not a prime number
252 is not a prime number
262 is not a prime number
273 is not a prime number
283 is a prime number
293 is a prime number
303 is not a prime number
313 is a prime number
323 is not a prime number
333 is not a prime number
343 is not a prime number
353 is a prime number
364 is not a prime number
374 is not a prime number
384 is not a prime number
394 is not a prime number

In [408]:
#10. Create a NumPy array representing daily temperatures for a month. Calculate and display the weekly averages.
daily_temp = np.array([21,19,27,28,20,23,18,22,23,19.5,21.5,22,23, 22.5, 23.0, 24.5, 25.2, 26.8, 27.3, 28.1, 29.0, 28.7, 27.4, 26.0, 24.8, 23.9, 22.6, 28, 27, 30])
week_first = np.average((daily_temp[1:8]))
second_week= np.average((daily_temp[8:15]))
third_week = np.average((daily_temp[15:22]))
print(f"first week {week_first}")
print(f"second week {second_week}")
print(f"third week {third_week}")


first week 22.428571428571427
second week 22.071428571428573
third week 27.085714285714285
